Test localization
jaanos/crypto-portal pull request #12
Opened 2018-10-11 07:18 UTC by FilicMia

2018-10-11 07:19 UTC, FilicMia commented
Test localization

2018-10-11 11:04 UTC, jaanos requested changes
I have added a few comments to your changes. Please apply before the changes can be accepted.

2018-10-11 11:04 UTC, jaanos commented on .gitignore
> +crypto.py
`crypto.py` is the main program and should not be in `.gitignore`. Instead, `*.mo` should be added, as it corresponds to generated binary files (the git hook should be updated to generate it).

2018-10-11 11:04 UTC, jaanos commented on cert.pem
> +-----BEGIN RSA PRIVATE KEY-----
This file should be deleted, as well as the `__pycache__` directory (not sure how they got added, since they are in `.gitignore`).

2018-10-11 11:04 UTC, jaanos commented on templates/substitution.stats.en.html
> +        <b>{{_("Most common two-letter words:")}}</b>{{_(" of, to, in, it, is, be, as, at,
This depends on the language of the ciphertext (not of the portal), so the initial text should be translated from the same string in both templates (from English, but I see that this has not yet been changed elsewhere), while the word list should not be translated.

2018-10-11 11:04 UTC, jaanos commented on timestamp.py
> +        f.write(key.publickey().exportKey('PEM'))
The web app should not write anything on the disk - in fact, the corresponding files are marked as read-only on the server. This code can go to a separate set-up helper script, while the main application should just assume that everything has been set up properly.

2018-10-21 18:56 UTC, jaanos approved these changes

2018-10-21 18:57 UTC, merged

2018-10-21 19:55 UTC, jaanos commented
Sorry for the late response - I finally got around to merging and testing on the server - you can check it at https://lkrv.fri.uni-lj.si/crypto-devel/. Note that the menu is now too long (at least on my screen), but that would need to be redone anyway.

If you are happy with the current state, I suggest that your commits (up to 298037a) be merged into the `localization` branch, and then I can rebase my commits on top of them (note that I made a few commits after merging this pull request). Commit bffa5f1 should not be included in working branches as it contains some `devel`-specific changes. If you want to include the latest work, just merge the `andreja110s/transposition-cipher` and `TomazSpehar/hash` branches.

As we have talked, the translations should go from English to Slovene (and eventually other languages). Please make sure that the units to be translated make sense - in particular, avoid breaking sentences into multiple units.